import { Button } from '@components/Form/Button'
import Head from 'next/head'
import React from 'react'

import HeroImg from '../assets/mockup.png'

import { Container, Content, Hero } from '@styles/pages/main'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Content>
          <Hero>
            <section>
              <span />
              <img src={HeroImg} alt="Mockup" />
            </section>
            <section>
              <h1>Fiber Three</h1>
              <p>
                Sistema de gerenciamento massivo de rede <br /> para provedores
              </p>

              <Button>Solicitar demonstração</Button>
            </section>
          </Hero>
        </Content>
      </Container>
    </>
  )
}
